### ISSUE TITLE
ConcurrentModificationException when filtering credit cards

### ISSUE THREAD

**Issue by RobDickinson** [philterd/phileas#147]
It looks like the latest version of `CreditCardFilter` has a case where it's attempting to modify a list while being iterated?

I can easily reproduce these exceptions:

```
java.util.ConcurrentModificationException
        at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:977)
        at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:899)
        at ai.philterd.phileas.services.filters.regex.CreditCardFilter.filter(CreditCardFilter.java:96)
        at ai.philterd.phileas.processors.unstructured.UnstructuredDocumentProcessor.process(UnstructuredDocumentProcessor.java:65)
        at ai.philterd.phileas.services.PhileasFilterService.filter(PhileasFilterService.java:214)
```

Relevant code from `CreditCardFilter`:

```
for(final Span span : spans) { // line 96

    final String creditCardNumber = input.substring(span.getCharacterStart(), span.getCharacterEnd())
            .replaceAll(" ", "")
            .replaceAll("-", "");

    if (!luhnCheckDigit.isValid(creditCardNumber)) {
        spans.remove(span);
    }

}
```

Obligatory SO link: https://stackoverflow.com/questions/223918/iterating-through-a-collection-avoiding-concurrentmodificationexception-when-re

**Comment by jzonthemtn** [comment]
Thanks. Surprised just now hitting that.

**Comment by RobDickinson** [comment]
Thanks for the quick fix! :-)
